# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
virt: lxd
group: edge
os:
  - linux
arch:
  - amd64
  - arm64
  - arm64-graviton2
julia:
  - 1.0
  - 1.3
  - nightly
env:
  matrix:
    - ""
    - "CMAKE_JL_BUILD_FROM_SOURCE=1"
    - "BINARYPROVIDER_COPYDEREF=true"
    - "CMAKE_JL_BUILD_FROM_SOURCE=1"
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false
branches:
  only: master
before_script:
  # Every 30 seconds, look for the build log file. If it exists, then
  # start watching its contents and printing them to stdout as they
  # change. This has two effects:
  #   1. it avoids Travis timing out because the build outputs nothing
  #   2. it makes it more obvious what part of the build, if any, gets stuck
  - while sleep 30; do tail ~/build/JuliaPackaging/CMake.jl/deps/build.log -f ; done &
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
